### ISSUE TITLE
Scheduler class is final

### ISSUE THREAD

**Issue by Quatja** [skytix-dev/mesos-scheduler-client#1]
Hi, Scheduler class is final and it means that I cannot to extend it, but at the same time this class has several protected methods (protected methods mean that they could be overrided, but it is impossible because of final class).
Basically I wanted to use sendCall method but it is protected for some reason. I suggest to make it public.

btw there are some call types which I would like to see in ScheduleRemote, for example 'message'

**Comment by h4xmd** [comment]
What is the use-case for needing to subclass the Scheduler?  The method is protected because it's only intended to be used upon by the SchedulerRemote.

If there's authentication you're after, then I'm happy to build that in.

**Comment by Quatja** [comment]
I just wanted to get sendCall somehow... I believe the perfect solution is to put sendCall into SchedulerRemote as a public method. Current public methods inside SchedulerRemote don't cover my needs, but sendCall allows to use any Call I want

**Comment by h4xmd** [comment]
What does the SchedulerRemote not allow?  Making the current methods public is not the intended design.  All the functions in SchedulerRemote represent all the operations you can do.

**Comment by Quatja** [comment]
I’m not able to send a Call with type Call.Type.MESSAGE

**Comment by h4xmd** [comment]
Awesome thanks!  I'll get that support added in.  I thought I had all the main operations defined but missed it.  Won't take too long

**Comment by h4xmd** [comment]
There should be a 1.0.15 available to download soon that has a SchedulerRemote.message(Call.Message) method for you to use.

**Comment by Quatja** [comment]
Thanks
